---
- name: Installing the provisioner required
  hosts: all
  become: yes
  tasks:
    - name: Installing Git
      package:
        name: git
        state: present

    - name: Installing Amazon SSM Agent
      package:
        name: "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm"
        state: present
      register: ssm_install_output
      ignore_errors: true
      changed_when: "'Complete!' in ssm_install_output.stdout"

    - name: Install CloudWatch Agent
      package:
        name: "https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.deb"
        state: present

    - name: Start and enable CloudWatch Agent
      service:
        name: amazon-cloudwatch-agent
        state: started
        enabled: yes

    - name: Installing Amazon Inspector
      shell: |
        curl -O https://inspector-agent.amazonaws.com/linux/latest/install &&
        sudo bash install
      register: inspector_install_output
      ignore_errors: true
      changed_when: "'Complete!' in inspector_install_output.stdout"

    - name: Installing Docker
      package:
        name: docker.io
        state: present
