---
- name: Installing the provisioner required
  hosts: all
  become: yes
  tasks:
    - name: Installing Git
      package:
        name: git
        state: present

    - name: Installing Amazon SSM Agent
      shell: sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
      register: ssm_install_output
      ignore_errors: true
      changed_when: "'Complete!' in ssm_install_output.stdout"

    - name: Download CloudWatch Agent ubuntu package
      get_url:
        url: "https://amazoncloudwatch-agent.s3.amazonaws.com/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb"
        dest: "/tmp/amazon-cloudwatch-agent.deb"
        mode: '0644'
      register: cw_download_output
      ignore_errors: true

    - name: Install CloudWatch Agent package
      yum:
        name: "/tmp/amazon-cloudwatch-agent.deb"
        state: present
      when: not cw_download_output.failed

    - name: Show CloudWatch installation output
      debug:
        var: cw_download_output

    - name: Start and enable CloudWatch Agent
      service:
        name: amazon-cloudwatch-agent
        state: started
        enabled: yes
      when: not cw_download_output.failed

    - name: Installing Amazon Inspector
      shell: |
        curl -O https://inspector-agent.amazonaws.com/linux/latest/install &&
        sudo bash install
      register: inspector_install_output
      ignore_errors: true
      changed_when: "'Complete!' in inspector_install_output.stdout"

    - name: Installing Docker
      package:
        name: docker
        state: present
